### ISSUE TITLE
Fix routing in navbar

### ISSUE THREAD

**Issue by MLJBrackett** [Mustafiz04/Covid-19-website#2]
When you are not on the main page and you click on routes such as - 'about', 'symptoms', and 'prevention' you are not routed correctly and stay on the page that you are currently active on.

**Comment by MLJBrackett** [comment]
Currently I am working on a fix for this, Ill send in the pull request soon.

**Comment by Mustafiz04** [comment]
Ya sure go for it. I am waiting.

**Comment by Mustafiz04** [comment]
Have you checked on your computer?? Still not work here.

**Comment by Mustafiz04** [comment]
> Have you checked on your computer?? Still not work here.

@MLJBrackett Please check, correct, and make a new pull request.

**Comment by MLJBrackett** [comment]
@Mustafiz04 The code works on my end, are you checking "https://covid-19-website.herokuapp.com/" or the master branch locally. You need to redeploy your website with the new code since it's still on an earlier version. 

![img](https://i.gyazo.com/cb2a7bd3dce5abc3c0a037c07c71e9cf.png)

As you can see on the right side, the website is not updated with my current changes to the 'href' property.

I'll test it on another computer soon.

**Comment by Mustafiz04** [comment]
Sorry, @MLJBrackett, I did not redeploy my code on Heroku.
Now it works perfectly.
Thank You.
