### ISSUE TITLE
Chrome error ('api' has already been declared') on several pages

### ISSUE THREAD

**Issue by chuckyroh** [Mustafiz04/Covid-19-website#8]
## Issue wit the variable `api` being declared more than once
- Chrome specifically refers to `home.js` as to the source of the issue

## Occurs on the following pages (by name on navbar)
- Country Wise
- State Wise
- India's Timeline

## Screenshot
![image](https://user-images.githubusercontent.com/12401186/96355646-b1dc2480-1098-11eb-950d-2fc3a7ab13fc.png)

**Comment by chuckyroh** [comment]
I can fix this error

**Comment by Mustafiz04** [comment]
Yes, you can. go for it.
